import React from "react";
import Head from "next/head";
import {
  AppBar,
  Box,
  Button,
  Container,
  Grid,
  List,
  ListItem,
  Typography,
} from "@mui/material";
import MenuIcon from "@mui/icons-material/Menu";
import classes from "./../styles/Home.module.css";
export default function layout(title, discription, children) {
  return (
    <div>
      <Head>
        <title>Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={classes.box}>
        <AppBar position="static" className={classes.appBar}>
          <Grid container spacing={3} justifyContent="center">
            <Grid item xs={4} display="flex">
              <MenuIcon />
              <div className={classes.firstBox}>Logo</div>
            </Grid>
            <Grid item xs={4} spacing={3}>
              <div className={classes.secondBox}>
                <Typography>Home</Typography>
                <Typography>About</Typography>
                <Typography>Feedback</Typography>
              </div>
            </Grid>
            <Grid item xs={4} justifyContent="flex-end">
              <div className={classes.thirdBox}>
                <Button color="inherit">Login</Button>
              </div>
            </Grid>
          </Grid>
        </AppBar>
        <Container>{children}</Container>
      </div>
      <footer className={classes.footer}>
        <Typography>All rights reserved.</Typography>
      </footer>
    </div>
  );
}
